### ISSUE TITLE
Unable to generate pdf

### ISSUE THREAD

**Issue by manishamittal16** [mamans86/tcexam-mobile-friendly#1]
When I tried with free answer and upload answer image ,then it gives same error in both files "report" on user side and "PDF".

![error](https://user-images.githubusercontent.com/64191398/88448746-77c70200-ce5e-11ea-997b-289292cc0cbe.PNG)

**Comment by mamans86** [comment]
this latest version https://github.com/mamans86/tcexam-mobile-friendly/releases/tag/20.07.29 has a print button that you can use to generate PDF.
