### ISSUE TITLE
Can student upload excel file instead of images ?

### ISSUE THREAD

**Issue by worldfellow** [mamans86/tcexam-mobile-friendly#4]
Currently file upload for images is working find but if student wants to upload excel file is that option available

**Comment by akhyariz** [comment]
Check your public configuration file (./public/config/tce_config_upload.php)

**Comment by mamans86** [comment]
yes you can allow XLS file extension by editing K_ALLOWED_UPLOAD_EXTENSIONS in public/config/tce_config_upload.php
